version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo Installing Terraform && wget -q https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip && unzip terraform_0.12.7_linux_amd64.zip -d /usr/local/bin && chmod +x /usr/local/bin/terraform
      - echo Branch name is $BRANCH
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Version name will be ${IMAGE_TAG}
      - TF_CLI_ARGS="-no-color"
  build:
    commands:
      - echo Build started on `date`
      - echo Initializing Terraform for branch $BRANCH
      - cd ./terraform && chmod +x ./terraform-init.sh && ./terraform-init.sh ${BRANCH}
      - export TF_VAR_env_name=${BRANCH} && export TF_VAR_version_tag=${IMAGE_TAG}
      - echo Planning infrastructure
      - terraform apply
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deployed app version ${IMAGE_TAG}
