version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo Installing Terraform && wget -q https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip && unzip terraform_0.12.7_linux_amd64.zip -d /usr/local/bin && chmod +x /usr/local/bin/terraform
      - echo Branch name is $CODEBUILD_SOURCE_VERSION
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Version name will be ${IMAGE_TAG}
      - TF_CLI_ARGS="-no-color"
  build:
    commands:
      - echo Build started on `date`
      - echo Privisioning ECS cluster
#      - chmod +x ./scripts/terraform_create_ecs_cluster.sh && ./scripts/terraform_create_ecs_cluster.sh
#      - ./scripts/docker-compose-push.sh ${IMAGE_TAG}
#      - echo Docker images pushed to ECR with tag ${IMAGE_TAG}
#      - echo Initializing Terraform
#      - cd ./terraform && terraform init >/dev/null
#      - terraform plan -var="version_tag=${IMAGE_TAG}"
  #      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
  #      - docker pull $REPO_URI:latest || true
  #      - docker build --cache-from $REPO_URI:latest --tag $REPO_URI:latest --tag $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
#      - echo Writing image definitions file...
#      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPO_URI:$IMAGE_TAG" | tee imagedefinitions.json
#artifacts:
#  files: imagedefinitions.json
