version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws --version
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Version name will be ${IMAGE_TAG}
  build:
    commands:
      - echo Build started on `date`
      - ./scripts/docker-compose-push.sh ${IMAGE_TAG}
      - echo Docker images pushed to ECR with tag ${IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $IMAGE_TAG >> version.txt
artifacts:
  files: version.txt
