version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws --version
      - echo Branch name is $BRANCH
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export MYSQL_HOST=127.0.0.1
      - export MYSQL_DB=db
      - export MYSQL_USER=root
      - export MYSQL_PASS=root
      - (docker stop some-mysql && docker rm some-mysql) || true
      - docker run --name some-mysql --rm -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=db -p 3306:3306 -d mysql:5.7
  build:
    commands:
      - echo Tests started on `date`
      - npm run installDeps && npm run beMigrations
      - npm run feUnitTests
      - npm run beUnitTests && npm run beFunctionalTests
  post_build:
    commands:
      - echo Tests completed on `date`
#      - echo Writing image definitions file...
#      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPO_URI:$IMAGE_TAG" | tee imagedefinitions.json
#artifacts:
#  files: imagedefinitions.json
