version: "3"

services:
  nginx:
    image: ${ECR_PREFIX}/nginx:${TAG}
    build: nginx
    environment:
      - IS_AWS=${IS_AWS}
      - BACKEND_HOST=backend
      - FRONTEND_HOST=frontend
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
  backend:
    image: ${ECR_PREFIX}/backend:${TAG}
    build:
      context: backend
    volumes:
      - ./backend:/app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DB=${MYSQL_DB}
    ports:
      - "8081:80"
    depends_on:
      - mysql
  frontend:
    image: ${ECR_PREFIX}/frontend:${TAG}
    build:
      context: frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8082:80

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASS}
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  frontend_app:
