version: "3"

services:
  nginx:
    build: nginx
    environment:
      - BACKEND_HOST=backend
      - FRONTEND_HOST=frontend
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
  backend:
    build:
      context: backend
    volumes:
      - ./backend:/app
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASS=${MYSQL_PASS:-password}
      - MYSQL_DB=${MYSQL_DB:-db}
      - MAILER_HOST=${MAILER_HOST:-smtp.mailtrap.io}
      - MAILER_USERNAME=${MAILER_USERNAME:-changeme}
      - MAILER_PASSWORD=${MAILER_PASSWORD:-changeme}
      - PLATFORM_OWNER_EMAIL=${PLATFORM_OWNER_EMAIL:-owner@example.com}
    ports:
      - "8081:80"
    depends_on:
      - mysql
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/app:cached
    ports:
      - 8082:80

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER:-user}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASS:-password}
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  frontend_app:
