version: "3"

services:
  nginx:
    build: nginx
    ports:
      - 8080:80
  backend:
    build:
      context: backend
    volumes:
      - "./backend:/app"
    ports:
      - "8081:80"
    depends_on:
      - mysql
  frontend:
    build:
      context: frontend
    ports:
      - 8082:80
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql
# Names our volume
volumes:
  mysql_data:
