version: '3'

services:
  frontend_builder:
    user: ${CURRENT_UID}
    build:
      context: frontend
      dockerfile: Dockerfile-builder
    volumes:
      - ./frontend:/app

  backend_unit_tests_runner:
    build:
      context: backend
    command: /app/scripts/tests-unit.sh
    volumes:
      - ./backend:/app
    depends_on:
      - mysql_for_tests
    environment:
      - MYSQL_HOST=mysql_for_tests
      - MYSQL_USER=tests
      - MYSQL_PASS=tests
      - MYSQL_DB=db_tests
      - TESTS_BACKEND_HOST=http://backend_functional_tests_lite_server/
  backend_functional_tests_runner:
    build:
      context: backend
    command: /app/scripts/tests-functional.sh
    volumes:
      - ./backend:/app
    depends_on:
      - mysql_for_tests
      - backend_functional_tests_lite_server
    environment:
      - MYSQL_HOST=mysql_for_tests
      - MYSQL_USER=tests
      - MYSQL_PASS=tests
      - MYSQL_DB=db_tests
      - TESTS_BACKEND_HOST=http://backend_functional_tests_lite_server/
  backend_functional_tests_lite_server:
    build:
      context: backend
    volumes:
      - ./backend:/app
    depends_on:
      - mysql_for_tests
    environment:
      - MYSQL_HOST=mysql_for_tests
      - MYSQL_USER=tests
      - MYSQL_PASS=tests
      - MYSQL_DB=db_tests

  # Execute backend functional tests towards this DB
  mysql_for_tests:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db_tests
      # So you don't have to use root, but you can if you like
      MYSQL_USER: tests
      # You can use whatever password you like
      MYSQL_PASSWORD: tests
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
