version: "3"

services:
  nginx:
    build: nginx
    ports:
      - 8080:80
  backend:
    build:
      context: backend
    volumes:
      - "./backend:/app"
    ports:
      - "8081:80"
  frontend:
    build:
      context: frontend
