<?php

namespace rest\versions\v1\actions\transaction;


use yii\web\MethodNotAllowedHttpException;

class DeleteAction extends \yii\rest\DeleteAction
{

    public function run($id)
    {
        throw new MethodNotAllowedHttpException('TODO');
        parent::run($id); // TODO: Change the autogenerated stub
    }

}