<?php

namespace rest\versions\v1\actions\transaction;


use yii\web\MethodNotAllowedHttpException;

class IndexAction extends \yii\rest\IndexAction
{

    public function run()
    {
        throw new MethodNotAllowedHttpException('TODO');

        return parent::run(); // TODO: Change the autogenerated stub
    }

}