<?php

namespace rest\versions\v1\actions\transaction;


use yii\web\MethodNotAllowedHttpException;

class ViewAction extends \yii\rest\ViewAction
{

    public function run($id)
    {
        throw new MethodNotAllowedHttpException('TODO');

        return parent::run($id); // TODO: Change the autogenerated stub
    }

}