<?php

namespace tests\functional;

use common\models\User;
use linslin\yii2\curl\Curl;
use PHPUnit\Framework\TestCase;
use yii\base\Exception;
use yii\helpers\Json;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;
use yii\web\UnauthorizedHttpException as UnauthorizedHttpExceptionAlias;

class FunctionalTestCase extends TestCase
{

    // The result of `php yii server`
    private $baseUrl = 'http://localhost:9009/';

    private $accessToken;

    /**
     * @param $path
     * @param string $method
     * @param array $params
     * @return array
     * @throws Exception
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     * @throws ServerErrorHttpException
     * @throws UnauthorizedHttpExceptionAlias
     */
    protected function apiCall($path, $method = 'GET', $params = [])
    {
        $curl = new Curl();
        $curl->setHeader('Accept', 'application/json');

        if ($this->accessToken) {
            $curl->setGetParams(['access-token' => $this->accessToken]);
        }

        $url = $this->baseUrl . $path;
        switch ($method) {
            case 'GET':
                $curl->setGetParams($params);
                $response = $curl->get($url);
                break;
            case 'POST':
                $curl->setPostParams($params);
                $response = $curl->post($url);
                break;
            case 'PUT':
                $curl->setPostParams($params);
                $response = $curl->put($url);
                break;
            case 'DELETE':
                $curl->setPostParams($params);
                $response = $curl->delete($url);
                break;
            default:
                throw new Exception('HTTP method not implemented for API call');
        }

        try {
            $response = Json::decode($response, true);
        } catch (Exception $e) {
            \Yii::error("Can not parse JSON response from API");
            throw $e;
        }

        // List of status codes here http://en.wikipedia.org/wiki/List_of_HTTP_status_codes
        switch ($curl->responseCode) {

            case 'timeout':
                //timeout error logic here
                throw new Exception('API call resulted in timeout:' . $path);
            case 200:
            case 201: // successfully created
            case 204: // successfully deleted
                //success logic here
                return $response;
            case 401:
                throw new UnauthorizedHttpExceptionAlias('Attempting to call an authenticated API with no token: ' . $method . " " . $url);
                break;
            case 403:
                throw new ForbiddenHttpException('Unauthorized API call: ' . $url);
            case 404:
                //404 Error logic here
                throw new NotFoundHttpException("URL not found:" . $path);
            case 422:
                \Yii::error($response);
                throw new ServerErrorHttpException('Model validation failed - error 422: ' . print_r($response, true));
            case 500:
                \Yii::error($response);
                throw new ServerErrorHttpException('API call during test threw 500 Internal Server Error');
            default:
                \Yii::error('Test error');
                \Yii::error($url);
                \Yii::error($method);
                \Yii::error($curl->responseCode);
                \Yii::error($response);
                throw new ServerErrorHttpException('API call during test resulted in an unknown error code:' . print_r($curl->responseCode,
                        1));
                break;
        }
    }

    /**
     * Create a new fake user with autogenerated username/password/email
     * @return User the newly created user
     * @throws ServerErrorHttpException
     */
    protected function createUser()
    {
        $faker = \Faker\Factory::create('en_US');
        $user = new User();
        $user->username = $faker->userName;
        $user->auth_key = md5(md5($faker->password));
        $user->password_hash = md5($faker->password);
        $user->email = $faker->email;
        $user->status = 10;
        if ($user->save()) {
            return $user;
        } else {
            \Yii::error($user->getErrors());
            throw new ServerErrorHttpException('Can not create a test user');
        }
    }

    protected function deleteUser($id)
    {
        $user = User::findOne($id);
        $deleted = $user->delete();
        return $deleted;
    }

    protected function logout()
    {
        $this->accessToken = null;
    }

    protected function loginAsUser($idUser = null)
    {
        if ($idUser != null) {
            $token = \Yii::$app->db->createCommand(
                'SELECT auth_key FROM user WHERE id=:id',
                [':id' => $idUser]
            )->queryScalar();
            $this->accessToken = $token;
            return;
        }
        $accessToken = $this->apiCall('v1/user/login', 'POST', [
            'username' => 'demo',
            'password' => 'demo',
        ]);
        $this->accessToken = $accessToken;
    }

    protected function createAccount()
    {
        // SUT
        return $this->apiCall(
            'v1/accounts',
            'POST',
            [
                'name' => '[TEST] My wallet',
            ]
        );
    }
}