<?php

namespace console\controllers;


class ServeController extends \yii\console\controllers\ServeController
{
    public function actionIndex($address = 'localhost')
    {
        return parent::actionIndex($address); // TODO: Change the autogenerated stub
    }

}