<?php

namespace console\controllers;


class ServerController extends \yii\console\controllers\ServeController
{
    public $docroot = '@rest/web';

    /**
     * @param string $address
     * @return int
     */
    public function actionIndex($address = 'localhost:9009')
    {
        return parent::actionIndex($address); // TODO: Change the autogenerated stub
    }

}