<?php

namespace console\controllers;


class TestServeController extends \yii\console\controllers\ServeController
{
    public $docroot = '@rest/web';

    public function init()
    {
        parent::init();

        $router = \Yii::getAlias('@rest/web/index-test.php');
        $this->router = $router;
    }

    /**
     * @param string $address
     *
     * @return int
     */
    public function actionIndex($address = 'localhost:9009')
    {
        return parent::actionIndex($address); // TODO: Change the autogenerated stub
    }

}