name: CDK Synth

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.10.0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'pnpm'
    - run: pnpm install
    - run: cd cdk && ENV_NAME=dummy npx cdk synth --all
