name: Deploy "develop"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/install-deps

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::364533559210:role/github-actions
          aws-region: us-east-1

      - run: ENV_NAME=dummy npx cdk synth --all
        working-directory: cdk

