name: Deploy "develop"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_deploy_infrastructure.yml
    with:
        branch: develop
